require_relative "bubble_sort.rb"
require_relative "counting_sort.rb"
require_relative "insertion_sort.rb"
require_relative "merge_sort.rb"
require_relative "quick_sort.rb"
require_relative "selection_sort.rb"