name: test-bash

on:
  push:
    paths:
      - 'Bash/**'
  pull_request:
    paths:
      - 'Bash/**'
  workflow_dispatch:

jobs:
  matrix:
    name: prepare-test-matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: generate-matrix
        id: set-matrix
        run: |-
          shopt -s globstar # Enable **
          shopt -s nullglob # Ignore empty glob
          make_matrix() {
            echo '{'
            echo '"test": ['
            f='false'
            for file in ./Bash/**/*.test.sh; do
              if "$f"; then
                echo -n ','
              else
                f='true'
              fi
              echo "\"${file}\""
            done
            echo ']'
            echo '}'
          }
          matrix="$(make_matrix)"
          echo "$matrix" | jq .
          echo "matrix=$(echo "$matrix" | jq -c .)" >> "${GITHUB_OUTPUT}"
  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    name: run-${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: run-test
        run: |-
          chmod +x '${{ matrix.test }}'
          . '${{ matrix.test }}'